### ISSUE TITLE
Split azure repo into multiple sub repo's

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#186]
So that we can version parts independently

**Done**
- [x] asb transport => NServiceBus.AzureServiceBus
- [x] storage transport => NServiceBus.AzureStorageQueues

**Left to do**
- [x] storage databus => NServiceBus.AzureBlobStorageDataBus  + acceptance tests
 - [x] ~~coordinate with Core for ATs when FileShareBased databus is taken out of Core => **Move to AzureDataBus repo**~~ replaced by https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/issues/2
- [x] :boom: storage persisters => NServiceBus.AzureStoragePersistence  + acceptance tests 
 - [x] ~~coordinate with Core for ATs~~ replaced by https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/9
- [x] hosts => NServiceBus.Host.AzureCloudService
 - [x] :boom: CS configuration (`ConfigurationSource`) and `SafeRoleEnvironment`=> moved to NServiceBus.Host.AzureCloudService
 - [x] ~~dynamic host => split into a feature (can run outside of Azure as well) => possibly not needed with new hosting options~~ replaced by https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/5
- [x] For NServiceBus.Azure change the contents of readme.md to explain changes in repos

:boom:  - indicates a breaking change

Versioning rules:

Major should change for every change for which either of these is true

- new major Azure sdk version
- new major nsb core version
- breaking api or behavioral change in code itself

**Comment by danielHalan** [comment]
+1
